// angular-app/src/app/components/dumb/header.component.ts
import {Component, OnInit} from '@angular/core'

// First part : display the title and the subtitle

// Second part : Since the routes are implemented (or not ?) you need now to add
//               some navLinks to navigate between the pages "Dashboard" and "Your wallet"

@Component({
  selector: 'app-header',
  template: `
    <div class="container">
      <div>
        <h1 class="title"></h1> <!-- title -->
        <h4 class="subtitle"></h4> <!-- subTitle -->
      </div>
      <div class="linkBox">
          <!-- need some navLinks -->
      </div>
    </div>
  `,
  styles: [
    `
      .container {
        background-color: #512da8;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        width: auto;
        height: 6rem;
      }

      .title {
        padding-top: 1rem;
        padding-left: 1.2rem;
        color: #ffffff;
        margin: 0;
      }

      .subtitle {
        color: #d1c4e9;
        padding-left: 1.2rem;
        margin: 0;
      }

      .linkBox {
        padding-right: 2rem;
        padding-top: 2.3rem;
      }

      .link {
        color: #ffffff;
        margin-left: 0.4rem;
        text-decoration: none;
      }
    `,
  ],
})
export class HeaderComponent implements OnInit {
  title = 'HackCoin'
  subTitle = 'Hello there! General Kenobi'
  constructor() {}

  ngOnInit() {}
}

// react-app/src/components/dumb/Header.js
import React from 'react'
import {HeaderStyled, Title, SubTitle, LinkBox} from './styledComponent/header'

//First part(introduction) => put this component in the right place.
//You want to display it in every page of your  app

//Second part(react-router) => create two links to navigate between the pages.
// "DashBoard" and "Your wallet" => wallet is in ../wallet/WalletDashBoard.js
// note StyledLink is a styled component that you can use for that.
// You can find it in the folder dumb/styledComponent/header.js

export const Header = () => (
  <HeaderStyled>
    <div>
      <Title>HackCoin</Title>
      <SubTitle>Hello there! General Kenobi</SubTitle>
    </div>
    <LinkBox>{/*
      TODO
    */}</LinkBox>
  </HeaderStyled>
)
