// react-app/src/App.js
import React, {Component} from 'react'
import {DashBoard} from './components/crypto-list/DashBoard'

// Firt part(intro) => display the Header component on the top of the app
// path ./components/dumb/Header

// Second part(react-router) => Implements the routing sytem using react-router
// Check https://github.com/ReactTraining/react-router for the doc
// hint : you need to display the cryptos, buy them, see your wallet and sell cryptos

// Third part => You need to setup your store to use it globally on the app !

class App extends Component {
  render() {
    return <DashBoard />
  }
}

export default App

// angular-app/src/app/app.component.ts
import {Component} from '@angular/core'

// Firt part(intro) => display the Header component on the top of the app

// Second part(routing) => Implements the routing sytem using the angular build-in router
// You need to implements the route on the app.module
// hint : you need to display the cryptos, buy them, see your wallet and sell cryptos

// Third part => nothing to do here !

@Component({
  selector: 'app-root',
  template: `
    <div>
      <app-dashboard></app-dashboard>
    </div>
  `,
  styles: [``],
})
export class AppComponent {
  title = 'HackCoin'
}
